line-length = 120
exclude = ["Brushshe/CTkMenuBar/*.py", "Brushshe/CTkMessagebox/*.py", "Brushshe/CTkColorPicker/*.py"]

[lint]
extend-select = ["F", "E", "W", "I", "N"]

[format]
quote-style = "double"
